// ---------------------------------------------------------------------
// CLIENTI: elenco, scheda con referenti cliccabili, cronologia, andamento economico, confronto.
// Il "cliente" di un movimento è clienteId oppure, per le quote di cantiere, il committente/affidataria del cantiere.
// ---------------------------------------------------------------------
function cantieriCliente(id){return stato.cantieri.filter(c=>c.committenteId===id||c.affidatariaId===id)}
function movimentiCliente(id){
  const ids=new Set(cantieriCliente(id).map(c=>c.id));
  return stato.movimenti.filter(m=>m.clienteId===id||quoteMovimentoPerCantiere(m).some(q=>ids.has(q.cantiereId)));
}
function fatturatoCliente(id,anno){
  let tot=0;
  for(const m of movimentiCliente(id)){ if(m.tipo==='uscita') continue; if(anno&&!(m.data||'').startsWith(String(anno))) continue; tot+=importoConSegno(m); }
  return tot;
}
function fatturatoPerCliente(anno){return stato.clienti.map(c=>({cliente:c,fatturato:fatturatoCliente(c.id,anno)})).filter(x=>x.fatturato>0).sort((a,b)=>b.fatturato-a.fatturato)}
function ultimoLavoroCliente(id){const date=cantieriCliente(id).map(c=>c.dataFine||c.dataInizio).filter(Boolean).concat(movimentiCliente(id).map(m=>m.data).filter(Boolean));return date.length?date.sort().pop():null}
function statisticheCliente(id){
  const cs=cantieriCliente(id).map(c=>({c,eco:economiaCantiere(c.id,stato.movimenti)}));
  const conMov=cs.filter(x=>x.eco.entrate||x.eco.uscite);
  const fatt=fatturatoCliente(id);
  const margini=conMov.map(x=>x.eco.marginePct).filter(x=>x!=null);
  const pag=movimentiCliente(id).filter(m=>m.tipo==='entrata').map(m=>({m,g:giorniPagamento(m)}));
  const conIncasso=pag.filter(x=>x.g!=null);
  const prev=stato.preventivi.filter(p=>p.clienteId===id);
  return {cantieri:cs,fatturato:fatt,margineMedioPct:margini.length?media(margini):null,migliore:conMov.slice().sort((a,b)=>b.eco.margine-a.eco.margine)[0]||null,peggiore:conMov.filter(x=>x.eco.margine<0).sort((a,b)=>a.eco.margine-b.eco.margine)[0]||null,giorniPagamento:conIncasso.length?media(conIncasso.map(x=>x.g)):null,pagamentiSenzaData:pag.length-conIncasso.length,pagamentiTot:pag.length,ultimoLavoro:ultimoLavoroCliente(id),preventivi:prev,tassoAccettazione:prev.length?prev.filter(p=>p.stato==='accettato').length/prev.filter(p=>p.stato!=='bozza').length*100:null};
}
VISTE.clienti=function(r){
  if(r.query.nuovo){setTimeout(()=>dialogoCliente(null),0);history.replaceState(null,'','#/clienti')}
  if(r.id) return vistaCliente(r.id);
  const vista=r.query.vista||ui.filtri.clientiVista||'elenco';
  const testa=html`<div class="testata"><div><h1>Clienti</h1><div class="sotto">${stato.clienti.length} soggetti · committenti, imprese affidatarie, fornitori</div></div><div class="azioni"><div class="gruppo-pulsanti"><button class="pulsante ${vista==='elenco'?'attivo':''}" data-azione="clienti-vista" data-valore="elenco">${icona('elenco')}Elenco</button><button class="pulsante ${vista==='confronto'?'attivo':''}" data-azione="clienti-vista" data-valore="confronto">${icona('bilancia')}Confronto</button><button class="pulsante ${vista==='professionisti'?'attivo':''}" data-azione="clienti-vista" data-valore="professionisti">${icona('persona')}Professionisti</button></div><button class="pulsante primario" data-azione="cliente-nuovo">${icona('piu')}Nuovo cliente</button></div></div>`;
  if(vista==='professionisti') return html`${testa}${vistaProfessionisti()}`;
  const righe=stato.clienti.map(c=>({c,st:statisticheCliente(c.id)}));
  if(vista==='confronto'){
    const conDati=righe.filter(x=>x.st.fatturato>0||x.st.cantieri.length);
    return html`${testa}<div class="scheda"><h3>Confronto fra clienti</h3><p class="secondario piccolo">Classifica per fatturato (imponibile), margine medio, numero di cantieri e tempi di pagamento: serve a capire con chi conviene lavorare. Dove la data di incasso non è registrata, il tempo di pagamento non c'è: non si stima.</p>
    ${conDati.length?html`<div class="griglia due">${graficoBarreOrizzontali(conDati.slice().sort((a,b)=>b.st.fatturato-a.st.fatturato).map(x=>({etichetta:x.c.ragioneSociale,valore:Math.round(x.st.fatturato),href:'#/clienti/'+x.c.id})),{formatta:v=>fEuro(v,0),titolo:'Fatturato'})}${graficoBarreOrizzontali(conDati.filter(x=>x.st.margineMedioPct!=null).sort((a,b)=>b.st.margineMedioPct-a.st.margineMedioPct).map(x=>({etichetta:x.c.ragioneSociale,valore:Math.round(x.st.margineMedioPct),href:'#/clienti/'+x.c.id})),{formatta:v=>fPct(v,0),titolo:'Margine medio'})}</div>`:''}
    ${tabella({id:'confronto',righe,chiaveOrd:'fatt',dir:'desc',href:x=>'#/clienti/'+x.c.id,colonne:[{chiave:'nome',titolo:'Cliente',principale:true,valore:x=>x.c.ragioneSociale},{chiave:'fatt',titolo:'Fatturato',num:true,valore:x=>x.st.fatturato,formatta:x=>fEuro(x.st.fatturato,0)},{chiave:'marg',titolo:'Margine medio',num:true,valore:x=>x.st.margineMedioPct==null?-9999:x.st.margineMedioPct,formatta:x=>x.st.margineMedioPct==null?html`<span class="silenzioso">—</span>`:html`<span class="${x.st.margineMedioPct<0?'da-compilare':''}">${fPct(x.st.margineMedioPct,0)}</span>`},{chiave:'n',titolo:'Cantieri',num:true,valore:x=>x.st.cantieri.length},{chiave:'pag',titolo:'Giorni di pagamento',num:true,valore:x=>x.st.giorniPagamento==null?9999:x.st.giorniPagamento,formatta:x=>x.st.giorniPagamento==null?html`<span class="silenzioso" title="Nessuna data di incasso registrata">dato non registrato</span>`:fNum(x.st.giorniPagamento,0)},{chiave:'ult',titolo:'Ultimo lavoro',valore:x=>x.st.ultimoLavoro||'',formatta:x=>x.st.ultimoLavoro?fData(x.st.ultimoLavoro):html`<span class="silenzioso">—</span>`}]})}</div>`;
  }
  return html`${testa}${tabella({id:'clienti',righe,chiaveOrd:'nome',href:x=>'#/clienti/'+x.c.id,colonne:[
    {chiave:'nome',titolo:'Ragione sociale',principale:true,valore:x=>x.c.ragioneSociale,formatta:x=>html`<b>${x.c.ragioneSociale}</b><br><span class="piccolo secondario">${[x.c.indirizzo.comune,x.c.indirizzo.provincia?'('+x.c.indirizzo.provincia+')':''].filter(Boolean).join(' ')}</span>`},
    {chiave:'ruoli',titolo:'Ruoli',formatta:x=>(x.c.ruoli||[]).map(r=>html`<span class="etichetta-tag">${RUOLI_CLIENTE[r]||r}</span> `)},
    {chiave:'n',titolo:'Cantieri',num:true,valore:x=>x.st.cantieri.length},
    {chiave:'fatt',titolo:'Fatturato',num:true,valore:x=>x.st.fatturato,formatta:x=>x.st.fatturato?fEuro(x.st.fatturato,0):html`<span class="silenzioso">—</span>`},
    {chiave:'marg',titolo:'Margine medio',num:true,valore:x=>x.st.margineMedioPct||0,formatta:x=>x.st.margineMedioPct==null?html`<span class="silenzioso">—</span>`:html`<span class="${x.st.margineMedioPct<0?'da-compilare':''}">${fPct(x.st.margineMedioPct,0)}</span>`},
    {chiave:'ult',titolo:'Ultimo lavoro',valore:x=>x.st.ultimoLavoro||'',formatta:x=>x.st.ultimoLavoro?fData(x.st.ultimoLavoro):html`<span class="silenzioso">—</span>`},
    {chiave:'stato',titolo:'Stato',formatta:x=>pillolaGenerica(STATI_CLIENTE[x.c.stato]||x.c.stato,x.c.stato==='attivo'?'valido':'neutro')},
  ],vuoto:vuoto({icona:'clienti',titolo:'Nessun cliente',azione:{testo:'Nuovo cliente',azione:'cliente-nuovo'}})})}`;
};
AZIONI['clienti-vista']=d=>{ui.filtri.clientiVista=d.valore;render()};
AZIONI['cliente-nuovo']=()=>dialogoCliente(null);
AZIONI['cliente-modifica']=d=>dialogoCliente(cliente(d.id));
function vistaCliente(id){
  const c=cliente(id); if(!c) return html`<div class="vuoto">${icona('attenzione')}<h3>Cliente non trovato</h3><a class="pulsante" href="#/clienti">Elenco</a></div>`;
  const st=statisticheCliente(id);
  const ling=linguettaAttiva('cliente:'+c.id,'scheda');
  return html`<div class="briciole"><a href="#/clienti">Clienti</a> › ${c.ragioneSociale}</div>
  <div class="testata"><div><h1>${c.ragioneSociale}</h1><div class="sotto">${(c.ruoli||[]).map(r=>RUOLI_CLIENTE[r]||r).join(', ')||''} · ${STATI_CLIENTE[c.stato]||''}${c.piva?' · P.IVA '+c.piva:''}</div></div><div class="azioni"><button class="pulsante" data-azione="interazione-nuova" data-id="${c.id}">${icona('piu')}Interazione</button><button class="pulsante primario" data-azione="cliente-modifica" data-id="${c.id}">${icona('modifica')}Modifica</button></div></div>
  <div class="griglia quattro mb">
    <div class="indicatore" style="cursor:default"><span class="etichetta">Fatturato totale</span><span class="valore md">${fEuro(st.fatturato,0)}</span></div>
    <div class="indicatore ${st.margineMedioPct!=null&&st.margineMedioPct<0?'critico':''}" style="cursor:default"><span class="etichetta">Margine medio</span><span class="valore md">${st.margineMedioPct!=null?fPct(st.margineMedioPct,0):'—'}</span></div>
    <div class="indicatore" style="cursor:default"><span class="etichetta">Giorni medi di pagamento</span><span class="valore md">${st.giorniPagamento!=null?fNum(st.giorniPagamento,0):'—'}</span><span class="nota">${st.pagamentiTot?(st.pagamentiSenzaData?st.pagamentiSenzaData+' incassi senza data registrata':'su '+st.pagamentiTot+' incassi'):'nessun incasso registrato'}</span></div>
    <div class="indicatore" style="cursor:default"><span class="etichetta">Ultimo lavoro</span><span class="valore md">${st.ultimoLavoro?fDataBreve(st.ultimoLavoro):'—'}</span><span class="nota">${st.cantieri.length} cantieri</span></div>
  </div>
  ${linguette('cliente:'+c.id,[{id:'scheda',testo:'Scheda e referenti',icona:'clienti'},{id:'cantieri',testo:'Cantieri',icona:'cantieri',contatore:st.cantieri.length||null},{id:'andamento',testo:'Andamento',icona:'avanzamento'},{id:'cronologia',testo:'Cronologia',icona:'orologio',contatore:(c.interazioni||[]).length||null},{id:'preventivi',testo:'Preventivi',icona:'preventivi',contatore:st.preventivi.length||null}],ling)}
  ${ling==='scheda'?schedaClienteAnagrafica(c):ling==='cantieri'?schedaClienteCantieri(c,st):ling==='andamento'?schedaClienteAndamento(c,st):ling==='cronologia'?schedaClienteCronologia(c):schedaClientePreventivi(c,st)}`;
}
function schedaClienteAnagrafica(c){
  const campo=(et,v,fmt)=>html`<div class="campo"><span class="etichetta-campo">${et}</span><div>${valoreODaCompilare(v,fmt)}</div></div>`;
  return html`<div class="griglia due"><div class="scheda"><h3>Anagrafica</h3><div class="campi">${campo('Partita IVA',c.piva)}${campo('Codice fiscale',c.cf)}<div class="campo largo"><span class="etichetta-campo">Indirizzo</span><div>${indirizzoTesto(c.indirizzo)||daCompilare()}</div></div>
    <div class="campo"><span class="etichetta-campo">Telefono</span><div>${c.telefono?contattoCliccabile('tel',c.telefono):daCompilare()}</div></div><div class="campo"><span class="etichetta-campo">Email</span><div>${c.email?contattoCliccabile('mail',c.email):daCompilare()}</div></div><div class="campo"><span class="etichetta-campo">PEC</span><div>${c.pec?contattoCliccabile('mail',c.pec):daCompilare()}</div></div><div class="campo"><span class="etichetta-campo">Sito</span><div>${c.sito?contattoCliccabile('web',/^https?:/.test(c.sito)?c.sito:'https://'+c.sito):html`<span class="silenzioso">—</span>`}</div></div>
    ${campo('Condizioni di pagamento',c.condizioniPagamento)}<div class="campo"><span class="etichetta-campo">Valutazione</span><div>${c.valutazione?'★'.repeat(c.valutazione)+'☆'.repeat(5-c.valutazione):html`<span class="silenzioso">—</span>`}</div></div>
    ${c.note?html`<div class="campo largo"><span class="etichetta-campo">Note</span><div>${c.note}</div></div>`:''}</div></div>
  <div class="scheda"><h3>Referenti <span class="azioni"><button class="pulsante piccolo" data-azione="referente-nuovo" data-id="${c.id}">${icona('piu','piccola')}Referente</button></span></h3>${(c.referenti||[]).length?html`<ul class="elenco-piatto">${c.referenti.map((r,i)=>html`<li><span class="persona-avatar">${iniziali(r.nome)}</span><span class="spazio"><b>${r.nome}</b> <span class="secondario">${r.ruolo||''}</span><br><span class="riga piccolo">${r.telefono?contattoCliccabile('tel',r.telefono):''} ${r.email?contattoCliccabile('mail',r.email):''}</span>${r.note?html`<br><span class="piccolo secondario">${r.note}</span>`:''}</span><button class="pulsante piccolo icona" data-azione="referente-modifica" data-id="${c.id}" data-i="${i}" aria-label="Modifica">${icona('modifica','piccola')}</button></li>`)}</ul>`:html`<p class="secondario">Nessun referente. Aggiungi telefono ed email: dal cantiere si chiama con un tocco.</p>`}</div></div>`;
}
function schedaClienteCantieri(c,st){
  return html`<div class="scheda"><h3>Cantieri</h3>${st.cantieri.length?tabella({righe:st.cantieri,href:x=>'#/cantieri/'+x.c.id,colonne:[{chiave:'n',titolo:'Cantiere',principale:true,formatta:x=>html`<b>${x.c.nome}</b> <span class="piccolo secondario">${x.c.anno}</span>`},{chiave:'r',titolo:'Ruolo',formatta:x=>x.c.committenteId===c.id?'committente':'impresa affidataria'},{chiave:'s',titolo:'Stato',formatta:x=>STATI_CANTIERE[x.c.stato]},{chiave:'e',titolo:'Entrate',num:true,formatta:x=>x.eco.entrate?fEuro(x.eco.entrate,0):''},{chiave:'m',titolo:'Margine',num:true,formatta:x=>(x.eco.entrate||x.eco.uscite)?html`<span class="${x.eco.margine<0?'da-compilare':''}">${fEuro(x.eco.margine,0)}${x.eco.marginePct!=null?' ('+fPct(x.eco.marginePct,0)+')':''}</span>`:html`<span class="silenzioso">—</span>`}]}):html`<p class="secondario">Nessun cantiere collegato.</p>`}</div>`;
}
function schedaClienteAndamento(c,st){
  const mov=movimentiCliente(c.id);
  if(!mov.length) return html`<div class="scheda"><h3>Andamento</h3><p class="secondario">Nessun movimento economico collegato a questo cliente: registra le fatture in <a href="#/budget">Budget</a>, assegnate ai suoi cantieri o direttamente al cliente.</p></div>`;
  const perAnno=new Map(),perMese=new Map();
  for(const m of mov){ if(m.tipo==='uscita'||!m.data) continue; const a=m.data.slice(0,4),k=m.data.slice(0,7); perAnno.set(a,(perAnno.get(a)||0)+importoConSegno(m)); perMese.set(k,(perMese.get(k)||0)+importoConSegno(m)); }
  const anni=Array.from(perAnno.entries()).sort();
  const mesi=Array.from(perMese.entries()).sort().slice(-24);
  const conMov=st.cantieri.filter(x=>x.eco.entrate||x.eco.uscite).sort((a,b)=>b.eco.margine-a.eco.margine);
  const entrate=somma(mov.filter(m=>m.tipo==='entrata'),m=>+m.imponibile||0),uscite=somma(mov.filter(m=>m.tipo==='uscita'),m=>+m.imponibile||0),note=somma(mov.filter(m=>m.tipo==='nota_credito'),m=>+m.imponibile||0);
  const pag=mov.filter(m=>m.tipo==='entrata'&&m.data).sort((a,b)=>a.data<b.data?-1:1).map(m=>({x:fDataBreve(m.data),y:giorniPagamento(m)}));
  return html`<div class="griglia due">
    <div class="scheda"><h3>Fatturato per anno</h3>${graficoBarre(anni.map(([a,v])=>({etichetta:a,valore:Math.round(v)})),{formatta:v=>fEuro(v,0),altezza:200})}</div>
    <div class="scheda"><h3>Fatturato per mese (ultimi 24)</h3>${graficoBarre(mesi.map(([k,v])=>{const {anno,mese}=daChiaveMese(k);return {etichetta:NOMI_MESI_BREVI[mese-1]+' '+String(anno).slice(2),valore:Math.round(v)}}),{formatta:v=>fEuro(v,0),altezza:200})}</div>
    <div class="scheda"><h3>Margine per cantiere</h3>${conMov.length?graficoBarreOrizzontali(conMov.map(x=>({etichetta:x.c.nome,valore:Math.round(x.eco.margine),href:'#/cantieri/'+x.c.id})),{formatta:v=>fEuro(v,0),media:media(conMov.map(x=>x.eco.margine))}):html`<p class="secondario">Nessun cantiere con movimenti.</p>`}<p class="piccolo secondario">Linea tratteggiata: margine medio. Le barre rosse sono perdite.</p></div>
    <div class="scheda"><h3>Entrate e uscite</h3>${graficoBarre([{etichetta:'Entrate',valore:Math.round(entrate)},{etichetta:'Uscite',valore:Math.round(uscite),classe:'s2'},{etichetta:'Note di credito',valore:Math.round(note),classe:'s3'},{etichetta:'Margine',valore:Math.round(entrate-uscite-note)}],{formatta:v=>fEuro(v,0),altezza:200})}</div>
    <div class="scheda"><h3>Tempi di pagamento</h3>${pag.some(p=>p.y!=null)?html`${graficoLinee([{nome:'giorni',punti:pag.map(p=>({x:p.x,y:p.y}))}],{formatta:v=>fNum(v,0)+' gg',altezza:200})}<p class="piccolo secondario">${pag.filter(p=>p.y==null).length?pag.filter(p=>p.y==null).length+' fatture senza data di incasso registrata: il dato non c\'è, non si stima.':''}</p>`:html`<p class="secondario">Nessuna data di incasso registrata: il dato non c'è, non si stima.</p>`}</div>
    <div class="scheda"><h3>Sintesi</h3><div class="campi"><div class="campo"><span class="etichetta-campo">Fatturato totale</span><div>${fEuro(st.fatturato,0)}</div></div><div class="campo"><span class="etichetta-campo">Margine medio</span><div>${st.margineMedioPct!=null?fPct(st.margineMedioPct,1):'—'}</div></div><div class="campo"><span class="etichetta-campo">Cantiere più redditizio</span><div>${st.migliore?html`<a href="#/cantieri/${st.migliore.c.id}">${st.migliore.c.nome}</a> (${fEuro(st.migliore.eco.margine,0)})`:'—'}</div></div><div class="campo"><span class="etichetta-campo">Cantiere in perdita</span><div>${st.peggiore?html`<a href="#/cantieri/${st.peggiore.c.id}" class="da-compilare">${st.peggiore.c.nome}</a> (${fEuro(st.peggiore.eco.margine,0)})`:'nessuno'}</div></div><div class="campo"><span class="etichetta-campo">Giorni medi di pagamento</span><div>${st.giorniPagamento!=null?fNum(st.giorniPagamento,0):'dato non registrato'}</div></div><div class="campo"><span class="etichetta-campo">Ultimo lavoro</span><div>${st.ultimoLavoro?fData(st.ultimoLavoro):'—'}</div></div></div></div>
  </div>`;
}
function schedaClienteCronologia(c){
  const inter=ordina(c.interazioni||[],'data','desc');
  return html`<div class="scheda"><h3>Cronologia della relazione <span class="azioni"><button class="pulsante piccolo" data-azione="interazione-nuova" data-id="${c.id}">${icona('piu','piccola')}Interazione</button></span></h3>${inter.length?html`<ul class="timeline">${inter.map(i=>html`<li><div class="quando">${fData(i.data)} · ${({mail:'Mail',telefonata:'Telefonata',incontro:'Incontro',offerta:'Offerta'})[i.tipo]||i.tipo}${i.cantiereId?html` · <a href="#/cantieri/${i.cantiereId}">${nomeCantiere(i.cantiereId)}</a>`:''}</div><div><b>${i.oggetto||''}</b>${i.testo?html`<br>${i.testo}`:''}</div><button class="pulsante piccolo discreto" data-azione="interazione-modifica" data-id="${c.id}" data-i="${(c.interazioni||[]).indexOf(i)}">${icona('modifica','piccola')}</button></li>`)}</ul>`:html`<p class="secondario">Nessuna interazione registrata. Segna mail, telefonate, incontri e offerte: fra sei mesi saprai cosa vi siete detti.</p>`}</div>`;
}
function schedaClientePreventivi(c,st){
  return html`<div class="scheda"><h3>Preventivi <span class="azioni"><a class="pulsante piccolo" href="#/preventivi?nuovo=1&cliente=${c.id}">${icona('piu','piccola')}Nuovo</a></span></h3>${st.preventivi.length?html`<p class="secondario">Tasso di accettazione: <b>${st.tassoAccettazione!=null&&!isNaN(st.tassoAccettazione)?fPct(st.tassoAccettazione,0):'—'}</b> (sugli inviati)</p>${tabella({righe:st.preventivi,href:p=>'#/preventivi/'+p.id,colonne:[{chiave:'n',titolo:'Numero',principale:true,formatta:p=>html`<b>${p.numero}/${p.anno}</b>`},{chiave:'d',titolo:'Data',formatta:p=>fData(p.data)},{chiave:'o',titolo:'Oggetto',formatta:p=>p.oggetto||''},{chiave:'s',titolo:'Stato',formatta:p=>pillolaStatoPreventivo(p.stato)},{chiave:'t',titolo:'Totale',num:true,formatta:p=>fEuro(totaliPreventivo(p).totale,0)}]})}`:html`<p class="secondario">Nessun preventivo per questo cliente.</p>`}</div>`;
}
function dialogoCliente(c){
  const nuovo=!c; c=c||{ruoli:[],stato:'attivo',indirizzo:{},referenti:[],interazioni:[]};
  const campi=[{nome:'ragioneSociale',etichetta:'Ragione sociale',obbligatorio:true,largo:true},{nome:'ruoli',etichetta:'Ruoli',tipo:'chip',largo:true,opzioni:Object.entries(RUOLI_CLIENTE).map(([v,t])=>({v,t}))},{nome:'piva',etichetta:'Partita IVA',valida:validatorePIVA},{nome:'cf',etichetta:'Codice fiscale',maiuscolo:true},{nome:'indirizzo.via',etichetta:'Indirizzo',largo:true},{nome:'indirizzo.cap',etichetta:'CAP'},{nome:'indirizzo.comune',etichetta:'Comune'},{nome:'indirizzo.provincia',etichetta:'Provincia',maiuscolo:true},{nome:'telefono',etichetta:'Telefono',tipo:'tel'},{nome:'email',etichetta:'Email',tipo:'email',valida:validatoreEmail},{nome:'pec',etichetta:'PEC',tipo:'email',valida:validatoreEmail},{nome:'sito',etichetta:'Sito web'},{nome:'condizioniPagamento',etichetta:'Condizioni di pagamento',segnaposto:'es. 60 gg d.f.f.m.'},{nome:'valutazione',etichetta:'Valutazione (1–5)',tipo:'select',opzioni:[1,2,3,4,5].map(v=>({v,t:'★'.repeat(v)}))},{nome:'stato',etichetta:'Stato',tipo:'select',vuoto:false,opzioni:Object.entries(STATI_CLIENTE).map(([v,t])=>({v,t}))},{nome:'note',etichetta:'Note',tipo:'textarea',largo:true}];
  return dialogoModulo(nuovo?'Nuovo cliente':'Modifica '+c.ragioneSociale,campi,c).then(v=>{if(!v)return;if(v.valutazione)v.valutazione=+v.valutazione;if(nuovo){const id=nuovoId('cl');esegui('Nuovo cliente '+v.ragioneSociale,s=>{s.clienti.push(Object.assign({id,referenti:[],interazioni:[],documenti:[]},v))});vai('clienti/'+id)}else esegui('Modificato cliente '+v.ragioneSociale,s=>{Object.assign(s.clienti.find(x=>x.id===c.id),v)})});
}
const CAMPI_REFERENTE=[{nome:'nome',etichetta:'Nome',obbligatorio:true},{nome:'ruolo',etichetta:'Ruolo'},{nome:'telefono',etichetta:'Telefono',tipo:'tel'},{nome:'email',etichetta:'Email',tipo:'email',valida:validatoreEmail},{nome:'note',etichetta:'Note',tipo:'textarea',largo:true}];
AZIONI['referente-nuovo']=async d=>{const v=await dialogoModulo('Nuovo referente',CAMPI_REFERENTE,{});if(!v)return;esegui('Aggiunto referente '+v.nome,s=>{s.clienti.find(x=>x.id===d.id).referenti.push(v)})};
AZIONI['referente-modifica']=async d=>{const c=cliente(d.id);const r=c.referenti[+d.i];const v=await dialogoModulo('Referente',CAMPI_REFERENTE,r,{pulsantiExtra:[{testo:'Elimina',classe:'pericolo',sinistra:true,fn:()=>{esegui('Eliminato referente',s=>{s.clienti.find(x=>x.id===d.id).referenti.splice(+d.i,1)});return null}}]});if(!v)return;esegui('Modificato referente',s=>{Object.assign(s.clienti.find(x=>x.id===d.id).referenti[+d.i],v)})};
const campiInterazione=()=>[{nome:'data',etichetta:'Data',tipo:'data',obbligatorio:true},{nome:'tipo',etichetta:'Tipo',tipo:'select',vuoto:false,opzioni:[{v:'mail',t:'Mail'},{v:'telefonata',t:'Telefonata'},{v:'incontro',t:'Incontro'},{v:'offerta',t:'Offerta'}]},{nome:'oggetto',etichetta:'Oggetto',obbligatorio:true,largo:true},{nome:'testo',etichetta:'Testo',tipo:'textarea',largo:true},{nome:'cantiereId',etichetta:'Cantiere collegato',tipo:'select',opzioni:stato.cantieri.map(c=>({v:c.id,t:c.nome}))}];
AZIONI['interazione-nuova']=async d=>{const v=await dialogoModulo('Nuova interazione',campiInterazione(),{data:oggi(),tipo:'mail'});if(!v)return;esegui('Registrata interazione',s=>{s.clienti.find(x=>x.id===d.id).interazioni.push(Object.assign({id:nuovoId('in')},v))})};
AZIONI['interazione-modifica']=async d=>{const c=cliente(d.id);const i=c.interazioni[+d.i];const v=await dialogoModulo('Interazione',campiInterazione(),i,{pulsantiExtra:[{testo:'Elimina',classe:'pericolo',sinistra:true,fn:()=>{esegui('Eliminata interazione',s=>{s.clienti.find(x=>x.id===d.id).interazioni.splice(+d.i,1)});return null}}]});if(!v)return;esegui('Modificata interazione',s=>{Object.assign(s.clienti.find(x=>x.id===d.id).interazioni[+d.i],v)})};
// ---- professionisti ----
function vistaProfessionisti(){
  return html`<div class="scheda"><h3>Professionisti <span class="azioni"><button class="pulsante piccolo" data-azione="professionista-nuovo">${icona('piu','piccola')}Nuovo</button></span></h3><p class="secondario piccolo">Progettisti, direttori dei lavori, coordinatori per la sicurezza, medico competente: le figure che entrano nelle sei figure del cantiere e nel POS.</p>${tabella({righe:stato.professionisti,onRiga:p=>dialogoProfessionista(p),colonne:[{chiave:'nome',titolo:'Nome',principale:true,formatta:p=>html`<b>${[p.titolo,p.nome].filter(Boolean).join(' ')}</b>`},{chiave:'ruoli',titolo:'Ruoli',formatta:p=>(p.ruoli||[]).map(r=>html`<span class="etichetta-tag">${RUOLI_PROFESSIONISTA[r]||r}</span> `)},{chiave:'ind',titolo:'Sede',formatta:p=>indirizzoTesto(p.indirizzo)},{chiave:'con',titolo:'Contatti',formatta:p=>html`${(p.telefoni||[]).map(t=>html`${contattoCliccabile('tel',t)} `)}${p.email?contattoCliccabile('mail',p.email):''}`},{chiave:'cant',titolo:'Cantieri',num:true,formatta:p=>stato.cantieri.filter(c=>[c.progettistaId,c.direttoreLavoriId,c.cseId,c.cspId].includes(p.id)).length}]})}</div>`;
}
AZIONI['professionista-nuovo']=()=>dialogoProfessionista(null);
function dialogoProfessionista(p){
  const nuovo=!p; p=p||{ruoli:[],indirizzo:{},telefoni:[]};
  const campi=[{nome:'titolo',etichetta:'Titolo',segnaposto:'Arch., Ing., Geom., Dott.'},{nome:'nome',etichetta:'Nome e cognome',obbligatorio:true},{nome:'ruoli',etichetta:'Ruoli che può ricoprire',tipo:'chip',largo:true,opzioni:Object.entries(RUOLI_PROFESSIONISTA).map(([v,t])=>({v,t}))},{nome:'indirizzo.via',etichetta:'Indirizzo',largo:true},{nome:'indirizzo.cap',etichetta:'CAP'},{nome:'indirizzo.comune',etichetta:'Comune'},{nome:'indirizzo.provincia',etichetta:'Provincia',maiuscolo:true},{nome:'telefoniTesto',etichetta:'Telefoni (separati da /)'},{nome:'email',etichetta:'Email',tipo:'email',valida:validatoreEmail},{nome:'pec',etichetta:'PEC',tipo:'email'},{nome:'cf',etichetta:'Codice fiscale',maiuscolo:true,valida:validatoreCF},{nome:'note',etichetta:'Note',tipo:'textarea',largo:true}];
  const val=clona(p);val.telefoniTesto=(p.telefoni||[]).join(' / ');
  return dialogoModulo(nuovo?'Nuovo professionista':'Modifica '+p.nome,campi,val,{pulsantiExtra:nuovo?[]:[{testo:'Elimina',classe:'pericolo',sinistra:true,fn:async()=>{if(stato.cantieri.some(c=>[c.progettistaId,c.direttoreLavoriId,c.cseId,c.cspId].includes(p.id))){avviso('È usato in un cantiere: toglilo prima da lì',{tipo:'errore'});return false}if(await conferma('Eliminare '+p.nome+'?',{pericolo:true})){esegui('Eliminato professionista',s=>{s.professionisti=s.professionisti.filter(x=>x.id!==p.id)});return null}return false}}]}).then(v=>{if(!v)return;v.telefoni=(v.telefoniTesto||'').split('/').map(x=>x.trim()).filter(Boolean);delete v.telefoniTesto;if(nuovo)esegui('Nuovo professionista '+v.nome,s=>{s.professionisti.push(Object.assign({id:nuovoId('pr')},v))});else esegui('Modificato professionista '+v.nome,s=>{Object.assign(s.professionisti.find(x=>x.id===p.id),v)})});
}
